apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0agk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0agk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0agk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0agk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0agk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jupo-tenant/rhtap-demo-app/hacbs-test-project-0agk@sha256:87b584d95e5b321a3d18aa9f2e0763502d002ef7d9ed26d950a3206b7b152c2b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
